[project]
name = "kiara-plugin-network_analysis"
version = "0.1.0"
description = "kiara modules and datatypes for network analysis."
authors = ["Markus Binsteiner <markus@frkl.io>"]
channels = ["conda-forge", "dharpa"]
platforms = ["linux-64", "win-64", "osx-64", "osx-arm64"]

[tasks]
install-dev-env = "pip install -e '.[dev_utils]'"
pre-commit-check = ".pixi/env/bin/pre-commit run --all-files"
kiara = ".pixi/env/bin/kiara"
show-versions = ".pixi/env/bin/kiara --version"
delete-context = ".pixi/env/bin/kiara context delete"

[dependencies]
python = "3.11.*"
pip = "23.3.*"
